function [command, matrix_state_new, state_nom,...
          state_est, state_true, uguess_new,...
          angular_v_des, P_kminl, P_kminlnom, r_k_hat]     = ALG_GP_MPC(veh_pose, trajref,mpc_params, veh_params,...
                                                             matrix_state,  con_params,true_mpc_params,...
                                                             uguess,d_GP, UseParallel, maxiter,... 
                                                             angular_v_des,  P_kminl, P_kminlnom,...
                                                             log, i)

% Projection point of the vehicle state
[~, index] = calc_nearest_point(veh_pose, trajref);
ref_pose   = calc_proj_pose(veh_pose(1:2), trajref(index, 1:3),trajref(index + 1, 1:3));
delta_x    = (veh_pose - ref_pose)';

% Command

         [command, matrix_state_new, state_nom,state_est,... 
          state_true, uguess_new, angular_v_des,...
          P_kminl, P_kminlnom,r_k_hat] =                      calc_gp_mpc(trajref, delta_x, veh_pose,... 
                                                              mpc_params,index, veh_params,...
                                                              matrix_state, con_params,...
                                                              true_mpc_params, uguess, d_GP,...
                                                              UseParallel, maxiter, angular_v_des,...
                                                              P_kminl, P_kminlnom,...
                                                              log, i)
end